// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azlmtjzerxcewdcmzmok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6bG10anplcnhjZXdkY216bW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NDgxOTQsImV4cCI6MjA1NzQyNDE5NH0.NaWi-q90bMtzLL5aYLgXhKLx2LUjdju2n7fTkzP19x4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);